# Generated by Django 2.2.3 on 2020-05-17 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teachers.TextQuestion'),
        ),
        migrations.AddField(
            model_name='multiplechoiceanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teachers.MultipleChoiceQuestion'),
        ),
        migrations.AddField(
            model_name='checkboxanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teachers.CheckboxQuestion'),
        ),
        migrations.AddField(
            model_name='booleananswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teachers.BooleanQuestion'),
        ),
    ]
