# Generated by Django 2.2.3 on 2020-08-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='US/Eastern', max_length=50),
        ),
    ]
