# Generated by Django 3.0.7 on 2020-07-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booleanquestion',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='checkboxquestion',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='textquestion',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
