# Generated by Django 2.2.3 on 2020-07-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20200707_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='school_year',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='term',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='unit',
        ),
        migrations.AddField(
            model_name='survey',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='frequency',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
