# Generated by Django 3.0.6 on 2021-01-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_auto_20200827_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='booleanquestion',
            name='anonymous',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='checkboxquestion',
            name='anonymous',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='anonymous',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='textquestion',
            name='anonymous',
            field=models.BooleanField(default=True),
        ),
    ]
